
package com.infy.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ItemFinder", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ItemFinder {


    /**
     * 
     * @return
     *     returns com.infy.client.ItemList
     */
    @WebMethod
    @WebResult(name = "allItems", targetNamespace = "")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://service/", className = "com.infy.client.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://service/", className = "com.infy.client.GetAllResponse")
    public ItemList getAll();

    /**
     * 
     * @param id
     * @return
     *     returns com.infy.client.Item
     */
    @WebMethod
    @WebResult(name = "selectedItem", targetNamespace = "")
    @RequestWrapper(localName = "getById", targetNamespace = "http://service/", className = "com.infy.client.GetById")
    @ResponseWrapper(localName = "getByIdResponse", targetNamespace = "http://service/", className = "com.infy.client.GetByIdResponse")
    public Item getById(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param iid
     * @return
     *     returns com.infy.client.Item
     */
    @WebMethod
    @WebResult(name = "selectedItem", targetNamespace = "")
    @RequestWrapper(localName = "getByItemId", targetNamespace = "http://service/", className = "com.infy.client.GetByItemId")
    @ResponseWrapper(localName = "getByItemIdResponse", targetNamespace = "http://service/", className = "com.infy.client.GetByItemIdResponse")
    public Item getByItemId(
        @WebParam(name = "iid", targetNamespace = "")
        int iid);

    /**
     * 
     * @param brand
     * @return
     *     returns com.infy.client.ItemList
     */
    @WebMethod
    @WebResult(name = "itemsOfTheBrand", targetNamespace = "")
    @RequestWrapper(localName = "getByBrand", targetNamespace = "http://service/", className = "com.infy.client.GetByBrand")
    @ResponseWrapper(localName = "getByBrandResponse", targetNamespace = "http://service/", className = "com.infy.client.GetByBrandResponse")
    public ItemList getByBrand(
        @WebParam(name = "brand", targetNamespace = "")
        String brand);

}
