
package com.infy.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ItemFinderServiceService", targetNamespace = "http://infy/services", wsdlLocation = "http://localhost:9090/SoapItemDocService?wsdl")
public class ItemFinderServiceService
    extends Service
{

    private final static URL ITEMFINDERSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.infy.client.ItemFinderServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.infy.client.ItemFinderServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:9090/SoapItemDocService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:9090/SoapItemDocService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ITEMFINDERSERVICESERVICE_WSDL_LOCATION = url;
    }

    public ItemFinderServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ItemFinderServiceService() {
        super(ITEMFINDERSERVICESERVICE_WSDL_LOCATION, new QName("http://infy/services", "ItemFinderServiceService"));
    }

    /**
     * 
     * @return
     *     returns ItemFinder
     */
    @WebEndpoint(name = "ItemFinderServicePort")
    public ItemFinder getItemFinderServicePort() {
        return super.getPort(new QName("http://infy/services", "ItemFinderServicePort"), ItemFinder.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ItemFinder
     */
    @WebEndpoint(name = "ItemFinderServicePort")
    public ItemFinder getItemFinderServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://infy/services", "ItemFinderServicePort"), ItemFinder.class, features);
    }

}
