
package clientpack;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Fortis", targetNamespace = "http://infy.com/", wsdlLocation = "http://localhost:9090/MetroServerProject?wsdl")
public class Fortis
    extends Service
{

    private final static URL FORTIS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(clientpack.Fortis.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = clientpack.Fortis.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:9090/MetroServerProject?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:9090/MetroServerProject?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        FORTIS_WSDL_LOCATION = url;
    }

    public Fortis(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Fortis() {
        super(FORTIS_WSDL_LOCATION, new QName("http://infy.com/", "Fortis"));
    }

    /**
     * 
     * @return
     *     returns MediClaim
     */
    @WebEndpoint(name = "MediClaimImplPort")
    public MediClaim getMediClaimImplPort() {
        return super.getPort(new QName("http://infy.com/", "MediClaimImplPort"), MediClaim.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MediClaim
     */
    @WebEndpoint(name = "MediClaimImplPort")
    public MediClaim getMediClaimImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://infy.com/", "MediClaimImplPort"), MediClaim.class, features);
    }

}
